### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by vogievetsky** [ElmerZhang/ezcrypto#4]
Hi, could you please add a license to your code, preferably MIT.
Your library is a dependency in https://github.com/markbao/speakeasy (which is MIT licensed)
Some companies, mine included can not use your code for legal reasons unless there is an explicit license attached to the code.

Thank you in advance,
Vadim

**Comment by ElmerZhang** [comment]
License added.

**Comment by markbao** [comment]
Thanks for the fast resolution @ElmerZhang!

**Comment by vogievetsky** [comment]
@ElmerZhang thank you for the lighting fast action!
