### ISSUE TITLE
AES CBC error

### ISSUE THREAD

**Issue by ghost** [ElmerZhang/ezcrypto#5]
Buffer.slice returns a "view" of the underlying buffer, so modifying the returned buffer will modify the underlying buffer. In this case, in aes.js, thisCryptedBlock is decrypted and no longer crypted.
The following is the fix:

```
for (var offset = 0; offset < c.length; offset += blockSizeInBytes) {
        // Save this crypted block
        var thisCryptedBlock = c.slice(offset, offset + blockSizeInBytes);
        var thisCryptedBlock2 = new Buffer(16);
        thisCryptedBlock.copy(thisCryptedBlock2, 0);
        // Decrypt block
        cipher._decryptblock(c, offset);
        // XOR decrypted block using previous crypted block
        for (var i = 0; i < blockSizeInBytes; i++) {
            c[offset + i] ^= prevCryptedBlock[i];
        }
        prevCryptedBlock = thisCryptedBlock2;
    }
```

**Comment by ElmerZhang** [comment]
Sorry, I'm not familiar with AES. Can you submit a pull request?

**Comment by ghost** [comment]
I think your test cases did not cover this common case of encrypting and
decrypting more than 15 bytes of data in CBC mode with padding. You may
want to check this for other modes as well

**Comment by ghost** [comment]
never mind, i just realised the entire code operates on Arrays, not Buffer
